DROP TABLE IF EXISTS USER_PREFERENCES;

CREATE TABLE USER_PREFERENCES
(
    PREF_TYPE VARCHAR2(15) NOT NULL, 
    PREF_VALUE VARCHAR2(300) NULL
);

INSERT INTO USER_PREFERENCES (PREF_VALUE,PREF_TYPE) VALUES ('3','noofclicks');
INSERT INTO USER_PREFERENCES (PREF_VALUE,PREF_TYPE) VALUES ('No','disableengage');

COMMIT;
